name: Deploy Yii2 App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest ./docker

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

      - name: SSH into EC2 and update Swarm service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker service rm yii2-app || true
            docker service create --name yii2-app --publish 8080:80 ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
