
# .github/workflows/deploy.yml

name: Deploy Yii2 App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3-
        
      - name: Install Docker using script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Install PHP & Composer
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip curl php php-cli php-zip php-dom composer docker.io docker-compose

      - name: Install PHP dependencies
        run: composer install

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker containers
        run: docker-compose up -d
